### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by next2non** [stokkes/docker-sstvproxy#1]
Hi,

I tried to run the docker and the channels populate my VLC, Plex, etc, but I get the following error. Can you please help me? Im running the docker on my Synology

INFO       - SmoothStreamsProxy -  check_token        
      - There was no token loaded, retrieving your first token...               
2018-08-15 06:13:32,003 - ERROR      - SmoothStreamsProxy -  get_auth_token     
      - There was no hash auth token returned from auth.SmoothStreams.tv...

Regards,
Tariq

**Comment by reinhardholl** [comment]
I get the same error

**Comment by next2non** [comment]
I managed to getting working, I put my sstv details inside the docket environment 

“-e YAP_USERNAME=<username> -e YAP_PASSWORD=<password> \
        -e YAP_SERVICE=<short_code_for_smoothstreams_service> “

And I deleted “proxysettings.json“ file from -v /config. It’s working fine now and tested it with Plex and TVheaded
